// Code generated by protoc-gen-go. DO NOT EDIT.
// source: legacyprototest.proto

package legacyprototest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LegacyGreeting struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Priority             int32    `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LegacyGreeting) Reset()         { *m = LegacyGreeting{} }
func (m *LegacyGreeting) String() string { return proto.CompactTextString(m) }
func (*LegacyGreeting) ProtoMessage()    {}
func (*LegacyGreeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c00d3be2aa68057, []int{0}
}

func (m *LegacyGreeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LegacyGreeting.Unmarshal(m, b)
}
func (m *LegacyGreeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LegacyGreeting.Marshal(b, m, deterministic)
}
func (m *LegacyGreeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LegacyGreeting.Merge(m, src)
}
func (m *LegacyGreeting) XXX_Size() int {
	return xxx_messageInfo_LegacyGreeting.Size(m)
}
func (m *LegacyGreeting) XXX_DiscardUnknown() {
	xxx_messageInfo_LegacyGreeting.DiscardUnknown(m)
}

var xxx_messageInfo_LegacyGreeting proto.InternalMessageInfo

func (m *LegacyGreeting) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LegacyGreeting) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func init() {
	proto.RegisterType((*LegacyGreeting)(nil), "LegacyGreeting")
}

func init() { proto.RegisterFile("legacyprototest.proto", fileDescriptor_4c00d3be2aa68057) }

var fileDescriptor_4c00d3be2aa68057 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x49, 0x4d, 0x4f,
	0x4c, 0xae, 0x2c, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0xb3, 0x94, 0xdc,
	0xb8, 0xf8, 0x7c, 0xc0, 0x12, 0xee, 0x45, 0xa9, 0xa9, 0x25, 0x99, 0x79, 0xe9, 0x42, 0x12, 0x5c,
	0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30,
	0xae, 0x90, 0x14, 0x17, 0x47, 0x41, 0x51, 0x66, 0x7e, 0x51, 0x66, 0x49, 0xa5, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x6b, 0x10, 0x9c, 0xef, 0x24, 0x18, 0xc5, 0x8f, 0x66, 0x41, 0x12, 0x1b, 0x98, 0x69,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x14, 0x74, 0x25, 0x91, 0x7a, 0x00, 0x00, 0x00,
}
