// Code generated by protoc-gen-go.
// source: github.com/monzo/typhon/proto/error/error.proto
// DO NOT EDIT!

/*
Package error is a generated protocol buffer package.

It is generated from these files:
	github.com/monzo/typhon/proto/error/error.proto

It has these top-level messages:
	StackFrame
	Error
*/
package error

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type StackFrame struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Line     int32  `protobuf:"varint,2,opt,name=line" json:"line,omitempty"`
	Method   string `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
}

func (m *StackFrame) Reset()         { *m = StackFrame{} }
func (m *StackFrame) String() string { return proto.CompactTextString(m) }
func (*StackFrame) ProtoMessage()    {}

type Error struct {
	Code    string            `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message string            `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Params  map[string]string `protobuf:"bytes,3,rep,name=params" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Stack   []*StackFrame     `protobuf:"bytes,4,rep,name=stack" json:"stack,omitempty"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func (m *Error) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Error) GetStack() []*StackFrame {
	if m != nil {
		return m.Stack
	}
	return nil
}
