// Code generated by protoc-gen-go.
// source: proto/error/error.proto
// DO NOT EDIT!

/*
Package error is a generated protocol buffer package.

It is generated from these files:
	proto/error/error.proto

It has these top-level messages:
	PlatformError
*/
package error

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type ErrorType int32

const (
	ErrorType_UNKNOWN               ErrorType = 0
	ErrorType_INTERNAL_SERVER_ERROR ErrorType = 1
	ErrorType_BAD_REQUEST           ErrorType = 2
	ErrorType_BAD_RESPONSE          ErrorType = 3
	ErrorType_TIMEOUT               ErrorType = 4
	ErrorType_NOT_FOUND             ErrorType = 5
	ErrorType_FORBIDDEN             ErrorType = 6
	ErrorType_UNAUTHORIZED          ErrorType = 7
)

var ErrorType_name = map[int32]string{
	0: "UNKNOWN",
	1: "INTERNAL_SERVER_ERROR",
	2: "BAD_REQUEST",
	3: "BAD_RESPONSE",
	4: "TIMEOUT",
	5: "NOT_FOUND",
	6: "FORBIDDEN",
	7: "UNAUTHORIZED",
}
var ErrorType_value = map[string]int32{
	"UNKNOWN":               0,
	"INTERNAL_SERVER_ERROR": 1,
	"BAD_REQUEST":           2,
	"BAD_RESPONSE":          3,
	"TIMEOUT":               4,
	"NOT_FOUND":             5,
	"FORBIDDEN":             6,
	"UNAUTHORIZED":          7,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}

type PlatformError struct {
	Type        ErrorType `protobuf:"varint,1,opt,name=type,enum=ErrorType" json:"type,omitempty"`
	Code        string    `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Description string    `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Context     []string  `protobuf:"bytes,4,rep,name=context" json:"context,omitempty"`
}

func (m *PlatformError) Reset()         { *m = PlatformError{} }
func (m *PlatformError) String() string { return proto.CompactTextString(m) }
func (*PlatformError) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("ErrorType", ErrorType_name, ErrorType_value)
}
